on:
  push:
    branches:
      - '**'

name: Test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: yarn install --frozen-lockfile
      - run: yarn test:types
      - run: yarn format
      - run: git diff --exit-code
      - run: yarn build
